### PR TITLE
Kuno Italian translation

### PR DESCRIPTION
**Pull request by v41bis**
added translate_it function with full italian translation and double checked

### CODE REVIEW

**Review by annemedia — APPROVED** [review]
Thank you so much. I applied few corrections and will post an update on X from @annemedia_web account shortly.

**Comment by jeffro256** [comment]
@v41bis can you confirm that this Kuno fundraiser link/addr belongs to you?

https://kuno.anne.media/fundraiser/z1dk/
4BKA4qLjZZ7eRBv1Y9LMTGYU8dMZNJyhG5zDE4RwYmib3Va1MevBDsc1M2mvWJAEP7ZJJpB79waJmZnRRrvGPTh1ADSLiGX

**Comment by annemedia** [comment]
Hey :) He might not see your comment, but I'd say yes, that's his. The link to his X profile here on Github corresponds to the links listed on the fundraiser's page.

**Comment by v41bis** [comment]
> @v41bis can you confirm that this Kuno fundraiser link/addr belongs to you?
> 
> https://kuno.anne.media/fundraiser/z1dk/ 4BKA4qLjZZ7eRBv1Y9LMTGYU8dMZNJyhG5zDE4RwYmib3Va1MevBDsc1M2mvWJAEP7ZJJpB79waJmZnRRrvGPTh1ADSLiGX

Sorry for the delay, yeah that's my fundraiser

**Pull request merged**
